name: ðŸ”– Version
on:
  push:
    branches:
      - main
      - dev

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  version:
    name: ðŸš€ Update Version
    runs-on: ubuntu-22.04
    if: ${{ github.event_name == 'push' }}

    steps:
      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v4

      - name: ðŸ”¢ Get HEAD commit hash
        id: get_head_hash
        run: echo "HEAD_HASH=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: ðŸ“… Get current date
        id: get_date
        run:
          echo "CURRENT_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT

      - name: ðŸ“ Update package.json
        run: |
          jq '
            if .["epic-stack"] then
              .["epic-stack"].head = "${{ steps.get_head_hash.outputs.HEAD_HASH }}" |
              .["epic-stack"].date = "${{ steps.get_date.outputs.CURRENT_DATE }}"
            else
              .["epic-stack"] = {
                "head": "${{ steps.get_head_hash.outputs.HEAD_HASH }}",
                "date": "${{ steps.get_date.outputs.CURRENT_DATE }}"
              }
            end
          ' package.json > temp.json && mv temp.json package.json

      - name: ðŸ’¾ Commit changes
        run: |
          git config --local user.email "kody@epicweb.com"
          git config --local user.name "kody"
          git add package.json
          git commit -m "Update epic-stack version [skip ci]"
          git push
